services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  logger:
    build:
      context: ./Logger
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      backend:
        condition: service_healthy

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
      - logger
